---
  - name: upgrade all rpm packages on RHEL/CentOS/Fedora?Alibaba Linux
    yum:
      name: "*"
      state: latest

  - name: upgrade docker from official repo
    yum:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      enablerepo: "https://download.docker.com/linux/centos/docker-ce.repo"

  - name: enable and start docker 
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - name: check docker available
    shell: 
      cmd: "docker --version|grep 'Docker version'"
      
  - name: pip install docker-py 
    pip:
      name:
        - pathlib>=1.0.1
        - docker-py>=1.10.6
        - click>=8.0.3
        - aliyun-python-sdk-core>=2.13.35
        - aliyun-python-sdk-slb>=3.3.8
        - aliyun-python-sdk-ecs>=4.24.13
        # - PyYAML>=5.3.0
      extra_args: -i https://mirrors.aliyun.com/pypi/simple