---
# tasks file for remove_image
  - name: remote nodes pip install docker-py
    pip:
      name:
        - pathlib>=1.0.1
        - docker-py>=1.10.6
        # - PyYAML>=5.3.0
      extra_args: -i https://mirrors.aliyun.com/pypi/simple

  - name: remove nodes local images one by one
    docker_image:
      state: absent
      force_absent: yes
      name: "{{ item.repository }}"
      tag: "{{ item.tag }}"
    with_items: "{{ image_tags }}"


