---
# tasks file for manner_applet_admin
  - name: "copy docker compose template file to remote /opt"
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: /opt/docker-compose-xxl-front.yml
      owner: root
      group: root
      mode: '0777'

  # - name: "install python-pip "
  #   shell: "wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python get-pip.py"

  - name: pip install docker-py 
    pip:
      name:
        - pathlib>=1.0.1
        - docker-py>=1.10.6
        # - PyYAML>=5.3.0
      extra_args: -i https://mirrors.aliyun.com/pypi/simple

  - name: "login admin-front"
    docker_login:
      registry_url: "{{ region1 }}"
      #registry_url: "{{ namespace1 }}"
      username: "{{ username1 }}"
      password: "{{ password1 }}"
      reauthorize: yes

  - name: pull admin-front
    docker_image:
      state: present
      force_source: yes
      name: "{{ namespace1 }}/admin-front:{{ admin_front_version }}"
      source: pull

  - name: pull schedule-admin
    docker_image:
      state: present
      force_source: yes
      name: "{{ namespace1 }}/schedule-admin:{{ schedule_admin_version }}"
      source: pull

  - name: "compose up"
    shell: "cd /opt && docker-compose -f docker-compose-xxl-front.yml up -d"


